webtalk_init -webtalk_dir /home/users/aarzooag/ee108/lab1/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/hash_round_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  9 15:59:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211854242_1777585578_210790717_967" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "72a58226-3278-45ec-9c6f-2ba6eb3df48c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "12a3f29a6692465abc8e44e32e77119d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Rocky" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Rocky Linux release 8.10 (Green Obsidian)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7742 64-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2245.780 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "202.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "4" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "37 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "124" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "18" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "232456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1972072981 -regid "211854242_1777585578_210790717_967" -xml /home/users/aarzooag/ee108/lab1/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/hash_round_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/users/aarzooag/ee108/lab1/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/hash_round_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/users/aarzooag/ee108/lab1/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/hash_round_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
