#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 09 16:27:14 PDT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim length_finder_tb_behav -key {Behavioral:sim_1:Functional:length_finder_tb} -tclbatch length_finder_tb.tcl -log simulate.log"
xsim length_finder_tb_behav -key {Behavioral:sim_1:Functional:length_finder_tb} -tclbatch length_finder_tb.tcl -log simulate.log

