# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/users/aarzooag/ee108/lab1/lab1/lab1.cache/wt [current_project]
set_property parent.project_path /home/users/aarzooag/ee108/lab1/lab1/lab1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths /home/users/aarzooag/ee108/hdmi_tx_ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/users/aarzooag/ee108/lab1/lab1/lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/arbiter.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/brute_force_synchronizer.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/button_press_unit.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/cam.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/debouncer.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/encoder.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/ff_lib.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/hash_rom.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/hash_round.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/hasher.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/dvi_defines.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/input_box.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/lab1_interface.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/length_finder.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/one_pulse.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/rotator.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/tcgrom.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/verifier.v
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/lab1_top.v
}
read_vhdl -library xil_defaultlib {
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/video_package_800x480.vhd
  /home/users/aarzooag/ee108/lab1/lab1starterfiles/vga_controller_800x480_60.vhd
}
read_ip -quiet /home/users/aarzooag/ee108/lab1/lab1/lab1.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet /home/users/aarzooag/ee108/lab1/lab1/lab1.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/users/aarzooag/ee108/lab1/lab1/lab1.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/users/aarzooag/ee108/lab1/lab1/lab1.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/users/aarzooag/ee108/lab1/lab1/lab1.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/users/aarzooag/ee108/lab1/lab1starterfiles/lab1.xdc
set_property used_in_implementation false [get_files /home/users/aarzooag/ee108/lab1/lab1starterfiles/lab1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab1_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab1_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab1_top_utilization_synth.rpt -pb lab1_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
