#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 02 21:24:18 PDT 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto bce472eabe894f0999f4822e2baf9d2e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab0_top_tb_behav xil_defaultlib.lab0_top_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto bce472eabe894f0999f4822e2baf9d2e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lab0_top_tb_behav xil_defaultlib.lab0_top_tb xil_defaultlib.glbl -log elaborate.log

